---
- name: Uninstall k3s on servers
  become: true
  hosts: masters
  tasks:
    - name: Ping hosts
      ansible.builtin.ping:

    - name: Uninstall k3s server
      ansible.builtin.command: /usr/local/bin/k3s-uninstall.sh
      register: uninstall_server_output
      changed_when: uninstall_server_output.rc == 0
      failed_when: uninstall_server_output.rc != 0

- name: Uninstall k3s on bootstrap servers
  become: true
  hosts: bootstrapMaster
  tasks:
    - name: Ping hosts
      ansible.builtin.ping:

    - name: Uninstall k3s server
      ansible.builtin.command: /usr/local/bin/k3s-uninstall.sh
      register: uninstall_bs_server_output
      changed_when: uninstall_bs_server_output.rc == 0
      failed_when: uninstall_bs_server_output.rc != 0
