all:
  children:
    pies:
      children:
        bootstrapMaster:
        masters:
        workers:

    bootstrapMaster:
      hosts:
        tower1:
          ansible_host: 192.168.178.50

    masters:
      hosts: {}

    workers:
      hosts:
        tower2:
          ansible_host: 192.168.178.52
        tower3:
          ansible_host: 192.168.178.56
        tower4:
          ansible_host: 192.168.178.53
