---
- name: Fetch kubeconfig from bootstrap master
  hosts: bootstrapMaster
  become: true
  tasks:
    - name: Ensure kubeconfig file exists
      ansible.builtin.stat:
        path: /etc/rancher/k3s/k3s.yaml
      register: kubeconfig_stat

    - name: Fail if kubeconfig is not found
      ansible.builtin.fail:
        msg: "Kubeconfig file not found on bootstrap master."
      when: not kubeconfig_stat.stat.exists

    - name: Fetch kubeconfig
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ./k3sconfig
        flat: true
