---
- name: Configure cgroups
  hosts: pies
  roles:
    - cgroups

- name: Install K3s bootstrap server
  hosts: bootstrapMaster
  roles:
    - bootstrap

- name: Install K3s servers
  hosts: masters
  roles:
    - masters

- name: Install K3s workers
  hosts: workers
  roles:
    - workers
