---
- name: Validate cluster connectivity
  hosts: pies
  become: true
  tasks:
    - name: Ping all nodes
      ansible.builtin.ping:

- name: Validate K3s is running on bootstrap master
  hosts: bootstrapMaster
  become: true
  tasks:
    - name: Check K3s server status
      ansible.builtin.systemd:
        name: k3s
        state: started
      register: k3s_status
      changed_when: false

    - name: Ensure K3s server is active
      ansible.builtin.debug:
        msg: "K3s server is active and running."
      when: k3s_status.status.ActiveState == "active"

- name: Validate K3s is running on worker nodes
  hosts: workers
  become: true
  tasks:
    - name: Check K3s agent status
      ansible.builtin.systemd:
        name: k3s-agent
        state: started
      register: k3s_agent_status
      changed_when: false

    - name: Ensure K3s agent is active
      ansible.builtin.debug:
        msg: "K3s agent is active and running."
      when: k3s_agent_status.status.ActiveState == "active"
