---
name: Ansible Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install Ansible and Ansible Lint
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Run Ansible Lint
        run: ansible-lint .
