---
name: Test Playbooks

on:
  schedule:
    - cron: "0 2 * * 0" # Runs every Sunday at 2 AM UTC

jobs:
  test-playbooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible

      - name: Run a test playbook
        run: |
          ansible-playbook -i inventory/hosts.yml playbooks/*.yml --syntax-check
          ansible-playbook -i inventory/hosts.yml playbooks/*.yml --check
